INSERT INTO MALHA_LOGISTICA (NOME, PONTO_INICIAL, PONTO_FINAL, DISTANCIA) VALUES ('SP', 'A', 'B', 10);
INSERT INTO MALHA_LOGISTICA (NOME, PONTO_INICIAL, PONTO_FINAL, DISTANCIA) VALUES ('SP', 'B', 'D', 15);
INSERT INTO MALHA_LOGISTICA (NOME, PONTO_INICIAL, PONTO_FINAL, DISTANCIA) VALUES ('SP', 'A', 'C', 20);
INSERT INTO MALHA_LOGISTICA (NOME, PONTO_INICIAL, PONTO_FINAL, DISTANCIA) VALUES ('SP', 'C', 'D', 30);
INSERT INTO MALHA_LOGISTICA (NOME, PONTO_INICIAL, PONTO_FINAL, DISTANCIA) VALUES ('SP', 'B', 'E', 50);
INSERT INTO MALHA_LOGISTICA (NOME, PONTO_INICIAL, PONTO_FINAL, DISTANCIA) VALUES ('SP', 'D', 'E', 30);

INSERT INTO MALHA_LOGISTICA (NOME, PONTO_INICIAL, PONTO_FINAL, DISTANCIA) VALUES ('RJ', 'A', 'B', 10);
INSERT INTO MALHA_LOGISTICA (NOME, PONTO_INICIAL, PONTO_FINAL, DISTANCIA) VALUES ('RJ', 'B', 'D', 15);
INSERT INTO MALHA_LOGISTICA (NOME, PONTO_INICIAL, PONTO_FINAL, DISTANCIA) VALUES ('RJ', 'A', 'C', 20);
INSERT INTO MALHA_LOGISTICA (NOME, PONTO_INICIAL, PONTO_FINAL, DISTANCIA) VALUES ('RJ', 'C', 'D', 30);
INSERT INTO MALHA_LOGISTICA (NOME, PONTO_INICIAL, PONTO_FINAL, DISTANCIA) VALUES ('RJ', 'B', 'E', 50);
INSERT INTO MALHA_LOGISTICA (NOME, PONTO_INICIAL, PONTO_FINAL, DISTANCIA) VALUES ('RJ', 'D', 'E', 30);


