INSERT INTO ENDERECO (LOGRADOURO, CIDADE,ESTADO, CEP, COMPLEMENTO, BAIRRO) VALUES ('Rua Boçoroca', 'São Paulo', 'SP', '04377190', 'Rua 1', 'Vila Mira');
INSERT INTO ENDERECO (LOGRADOURO, CIDADE,ESTADO, CEP, COMPLEMENTO, BAIRRO) VALUES ('Rua Boçoroca', 'São Paulo', 'SP', '04377190', 'Rua 1', 'Vila Mira');
INSERT INTO ENDERECO (LOGRADOURO, CIDADE,ESTADO, CEP, COMPLEMENTO, BAIRRO) VALUES ('Rua Boçoroca', 'São Paulo', 'SP', '04377190', 'Rua 1', 'Vila Mira');
INSERT INTO ENDERECO (LOGRADOURO, CIDADE,ESTADO, CEP, COMPLEMENTO, BAIRRO) VALUES ('Rua Boçoroca', 'São Paulo', 'SP', '04377190', 'Rua 1', 'Vila Mira');
INSERT INTO ENDERECO (LOGRADOURO, CIDADE,ESTADO, CEP, COMPLEMENTO, BAIRRO) VALUES ('Rua Boçoroca', 'São Paulo', 'SP', '04377190', 'Rua 1', 'Vila Mira');
INSERT INTO ENDERECO (LOGRADOURO, CIDADE,ESTADO, CEP, COMPLEMENTO, BAIRRO) VALUES ('Rua Boçoroca', 'São Paulo', 'SP', '04377190', 'Rua 1', 'Vila Mira');
INSERT INTO ENDERECO (LOGRADOURO, CIDADE,ESTADO, CEP, COMPLEMENTO, BAIRRO) VALUES ('Rua Boçoroca', 'São Paulo', 'SP', '04377190', 'Rua 1', 'Vila Mira');



