CREATE TABLE ENDERECO(
	ID          INTEGER IDENTITY PRIMARY KEY,
	LOGRADOURO  VARCHAR(50) NOT NULL,
	CIDADE      VARCHAR(50) NOT NULL,
	ESTADO      VARCHAR(2)  NOT NULL,
	CEP         VARCHAR(9)  NOT NULL,
        COMPLEMENTO VARCHAR(50),
        BAIRRO      VARCHAR(50)
);



