CREATE TABLE MALHA_LOGISTICA(
	ID   INTEGER IDENTITY PRIMARY KEY,
	NOME VARCHAR(50)         NOT NULL,
	PONTO_INICIAL VARCHAR(50) NOT NULL,
	PONTO_FINAL  VARCHAR(50) NOT NULL,
	DISTANCIA    DOUBLE      NOT NULL
);



